name: Space Launches CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - name: Use node js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"      # Runs a set of commands using the runners shell
      - name: install packages
        run: npm install    
      - name: build client
        run: npm run build --prefix client
